language: node_js
node_js:
  - 0.10
services:
  - mongodb
  - rabbitmq
addons:
  apt:
    packages:
      - git
      - make
      - gcc
      - g++
      - libssl-dev
      - cmake
      - libglib2.0-dev
      - pkg-config
      - libboost-regex-dev
      - libboost-thread-dev
      - libboost-system-dev
      - liblog4cxx10-dev
      - openjdk-6-jre
      - curl
      - libboost-test-dev
      - yasm
      - libvpx.
      - libx264.
install:
  - ./scripts/installTravisDeps.sh
script: ./scripts/installErizo.sh && ./scripts/installNuve.sh
