language: node_js
os:
  - osx
  - linux
cache:
  directories:
  - node_modules
  - cache
node_js:
  - 0.10
services:
  - mongodb
  - rabbitmq
addons:
  apt:
    packages:
      - git
      - make
      - gcc
      - g++
      - libssl-dev
      - cmake
      - libglib2.0-dev
      - pkg-config
      - libboost-regex-dev
      - libboost-thread-dev
      - libboost-system-dev
      - liblog4cxx10-dev
      - openjdk-6-jre
      - curl
      - libboost-test-dev
      - yasm
      - libvpx.
      - libx264.
before_install:
  # OSX
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then   ./scripts/installMacDeps.sh --unattended --disable-services --use-cache;    fi

  # LINUX
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then ./scripts/installTravisDeps.sh; fi
script: ./scripts/installErizo.sh && ./scripts/installNuve.sh
