version: 2.0

jobs:
  build:
    docker:
      - image: circleci/node:6
    working_directory: /tmp/licode
    steps:
      - checkout

      - setup_remote_docker

      # build and push Docker image
      - run: |
          docker build -t lynckia/licode:test
